import { atom } from 'nanostores';
import type { DocxTheme } from '~/lib/markdown/theme';

/**
 * Pending DOCX artifacts — documents generated by the AI in a chat that
 * does NOT yet have an initialized workspace.
 *
 * WHY this exists:
 *   When the AI emits a `<docxartifact>` block, the previous behaviour
 *   was to immediately `workbenchStore.showWorkbench.set(true)` and
 *   `currentView.set('document')`. That had two bad side-effects:
 *     1. The chat visually became a "project chat" (workbench panel
 *        opened) even though no project existed.
 *     2. The chat was implicitly considered project-linked because
 *        `showWorkbench` was true, which tripped workspace_guardrails
 *        and other "is this a project chat?" heuristics.
 *
 *   The user's requested behaviour:
 *     - If no workspace is initialized when the docx is generated,
 *       save the docx in localStorage (keyed by chatId) but keep the
 *       chat as a normal chat (no workbench).
 *     - If a workspace is later initialized in the SAME chat (e.g. the
 *       AI calls inject_template, the user picks a starter template,
 *       or the chat is auto-promoted to a project), migrate the pending
 *       docx into the workspace so it lives alongside the project files.
 *     - Any docx generated AFTER workspace init goes straight into the
 *       workspace (the existing docxArtifactStore path).
 *
 * SHAPE:
 *   Record<chatId, { markdown, messageId, theme }>
 *
 *   We only store the LATEST docx per chat — matches the existing
 *   docxArtifactStore's "latest-wins" semantics. Older pending docxs
 *   for the same chat are overwritten.
 *
 * PERSISTENCE: nanostores has no `effect` helper, so we persist
 * explicitly inside each mutation function.
 */

export interface PendingDocx {
  markdown: string;
  messageId: string;
  theme: DocxTheme | null;
  createdAt: string;
}

const STORAGE_KEY = 'amplify_pending_docx_artifacts';

function readFromStorage(): Record<string, PendingDocx> {
  if (typeof window === 'undefined') {
    return {};
  }

  try {
    const raw = localStorage.getItem(STORAGE_KEY);

    if (!raw) {
      return {};
    }

    const parsed = JSON.parse(raw);

    if (!parsed || typeof parsed !== 'object') {
      return {};
    }

    return parsed as Record<string, PendingDocx>;
  } catch {
    return {};
  }
}

function writeToStorage(value: Record<string, PendingDocx>): void {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(value));
  } catch (e) {
    console.error('[pendingDocx] Failed to persist:', e);
  }
}

export const pendingDocxStore = atom<Record<string, PendingDocx>>(readFromStorage());

function persist(): void {
  writeToStorage(pendingDocxStore.get());
}

/** Save a docx as pending for the given chatId. Latest-wins per chat. */
export function setPendingDocx(chatId: string, docx: Omit<PendingDocx, 'createdAt'>): void {
  const next = { ...pendingDocxStore.get() };
  next[chatId] = { ...docx, createdAt: new Date().toISOString() };
  pendingDocxStore.set(next);
  persist();
}

/** Read (and remove) the pending docx for a chat. Returns undefined if none. */
export function takePendingDocx(chatId: string): PendingDocx | undefined {
  const current = pendingDocxStore.get();
  const docx = current[chatId];

  if (!docx) {
    return undefined;
  }

  const next = { ...current };
  delete next[chatId];
  pendingDocxStore.set(next);
  persist();

  return docx;
}

/** Peek the pending docx for a chat without removing it. */
export function peekPendingDocx(chatId: string): PendingDocx | undefined {
  return pendingDocxStore.get()[chatId];
}

/** Remove the pending docx for a chat (e.g. on chat delete). */
export function clearPendingDocx(chatId: string): void {
  const current = pendingDocxStore.get();

  if (!(chatId in current)) {
    return;
  }

  const next = { ...current };
  delete next[chatId];
  pendingDocxStore.set(next);
  persist();
}

// Cross-tab sync.
if (typeof window !== 'undefined') {
  window.addEventListener('storage', (e) => {
    if (e.key === STORAGE_KEY) {
      pendingDocxStore.set(readFromStorage());
    }
  });
}
