/**
 * Server-side registry for in-flight template loads.
 *
 * PURPOSE
 * -------
 * inject_template.execute (in stream-text.ts) needs to BLOCK until the client
 * confirms all template files have been written to the WebContainer. The
 * client writes files in parallel via writeFilesParallel, then POSTs to
 * /api/template-loaded with the loadId + WriteProgress.
 *
 * This module is the bridge:
 *   - execute() calls `await waitForTemplateLoad(loadId)` — returns a Promise
 *     that resolves when the client signals completion (or rejects on timeout).
 *   - The /api/template-loaded route calls `resolveTemplateLoad(loadId, progress)`.
 *
 * WHY A MODULE-LEVEL MAP
 * ----------------------
 * The execute function and the API route are different request handlers in
 * the same long-lived server process (Cloudflare Worker / Node). A module-
 * level Map is the simplest way to share state between them without a
 * database round-trip. Entries are cleaned up immediately on resolve/timeout
 * to avoid memory leaks.
 *
 * TIMEOUT
 * -------
 * Default 120s — large templates (400+ files) at concurrency 12 should
 * complete in well under 60s, but we leave headroom for slow networks /
 * slow devices. On timeout, execute() returns a partial-success result so
 * the AI can continue (with a warning).
 */

export interface TemplateLoadProgress {
  loadId: string;
  done: number;
  total: number;
  failed: Array<{ path: string; error: string }>;

  /** ISO timestamp — when the client signaled completion. */
  completedAt: string;
}

interface PendingLoad {
  resolve: (progress: TemplateLoadProgress) => void;
  reject: (error: Error) => void;
  startedAt: number;
  timeoutTimer: ReturnType<typeof setTimeout>;

  /** Pre-registered file count — used for sanity-check on resolve. */
  expectedTotal: number;

  /**
   * The file list the client should write. Fetched via
   * GET /api/template-files?loadId=X. Cleared on resolve/timeout to free
   * memory (file lists can be large — 400 files × ~10KB each = ~4MB).
   */
  files: Array<{ path: string; content: string }>;
}

const DEFAULT_TIMEOUT_MS = 120_000;

/*
 * Module-level registry. In Cloudflare Workers, each isolate has its own
 * module scope, so this Map is per-isolate (not shared across the planet).
 * That's fine — the client POST that resolves a load always lands on the
 * same isolate as the execute() that started it (same chat session, same
 * dataStream connection).
 */
const pendingLoads = new Map<string, PendingLoad>();

/**
 * Register a pending template load. Returns a Promise that resolves when
 * the client signals completion (via resolveTemplateLoad) or rejects on
 * timeout.
 *
 * @param loadId      unique ID for this load (generated by execute)
 * @param files       file list the client will fetch + write in parallel
 * @param timeoutMs   how long to wait before giving up (default 120s)
 */
export function waitForTemplateLoad(
  loadId: string,
  files: Array<{ path: string; content: string }>,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<TemplateLoadProgress> {
  return new Promise<TemplateLoadProgress>((resolve, reject) => {
    const timeoutTimer = setTimeout(() => {
      const pending = pendingLoads.get(loadId);

      if (pending) {
        pendingLoads.delete(loadId);
        reject(new Error(`Template load ${loadId} timed out after ${timeoutMs}ms`));
      }
    }, timeoutMs);

    pendingLoads.set(loadId, {
      resolve,
      reject,
      startedAt: Date.now(),
      timeoutTimer,
      expectedTotal: files.length,
      files,
    });
  });
}

/**
 * Get the file list for a pending load (called by /api/template-files route).
 *
 * Returns the file list, or undefined if no load with that ID is pending
 * (e.g. already completed, timed out, or never registered).
 *
 * The file list is KEPT in the registry after this call — the client may
 * fetch it multiple times (e.g. on retry). It's cleared only when the load
 * resolves or times out.
 */
export function getTemplateFilesForLoad(loadId: string): Array<{ path: string; content: string }> | undefined {
  return pendingLoads.get(loadId)?.files;
}

/**
 * Resolve a pending template load (called by /api/template-loaded route).
 *
 * Returns true if a matching pending load was found and resolved, false
 * if no load with that ID is pending (e.g. timeout already fired, or the
 * client signaled twice).
 */
export function resolveTemplateLoad(
  loadId: string,
  progress: Omit<TemplateLoadProgress, 'loadId' | 'completedAt'>,
): boolean {
  const pending = pendingLoads.get(loadId);

  if (!pending) {
    return false;
  }

  clearTimeout(pending.timeoutTimer);
  pendingLoads.delete(loadId);

  pending.resolve({
    loadId,
    done: progress.done,
    total: progress.total,
    failed: progress.failed,
    completedAt: new Date().toISOString(),
  });

  return true;
}

/**
 * Cancel a pending template load (e.g. if execute catches an error before
 * the client signals). Returns true if a load was cancelled, false if not
 * pending.
 */
export function cancelTemplateLoad(loadId: string): boolean {
  const pending = pendingLoads.get(loadId);

  if (!pending) {
    return false;
  }

  clearTimeout(pending.timeoutTimer);
  pendingLoads.delete(loadId);

  return true;
}

/**
 * Introspection helper — for tests + debugging. Returns the count of
 * currently-pending loads.
 */
export function pendingLoadCount(): number {
  return pendingLoads.size;
}
